env:
  global:
    - name: BITBUCKET_USER_NAME
    - secure: duCf4j0NVm/JdYCOa5PsX7MUBncl326iiMXPG7eOSSSgzYDxsV+7f8O43Ui6KeDLJT29dEU+fTe5ege49skGjWrDiXLbYShxxMd1DJx/ulPxynvrm90O07UHltPlMYl9HztwGqkB0p6WlN4yHiUf2tAYS6u5a5UWYbbrQvjIa3LlHlYfnqoC1fbneBn44cL/j79ukSQrGoyNSsvqbBMOkVsrIixTaHeWNumP75Kv5z9cWRUOtuY507bQA9Aj8sYvrKRAjXTB+ey4tyb1aD2u6JYStFsKC4133W91kttc+D3YHfpWdEwe14R7/XPL2n+euzRQhVr4miR+F/1pXSoAvqPlPWi9KhXlhlHas7JRL40SeGmOuERX+lyFz4kG72rE/eRTJLxEpHB16BdW30fENpUZ0zCQuiSORdmigD4glowxtf6vX7KcKlHvtw3X2axjTFzPKAbL60v1t4HgE9eL2ZW2pTYnik/GT3zMA3xLYSxOUW4x0dAlOtskLEf1fFfMVZkg+mJflp2LfYgwIh/Ddn1HQZYbYoyx4kgG6LXRvKU1ZQFWSbjNYZUm/g5pReBp3+cR1ZOZiIkk2YaUpcrtlFazOj2ieXD21OBo0m5GaEyzrPaU7ZyiOBzMt9olTILmjxTfnIlUJQJr1yo2Jzf3hKEFpRTmeJYFtGqs+bJQKrA= # BITBUCKET_USER_NAME
    - name: BITBUCKET_USER_PASSWORD
    - secure: jwnuTcfHyjjJkEtRDBAVua68bt1Tygtw6qy4Qkf1hB5lq04ehvBVEqH+oAjdjl+wNqmyeGkt8E7wdAs3K+3eURbHlxBO/1hQyf2VZZz0JwTJyl/dt3eBuinHq5ZoUaKO69+rvp2AB8MIM8C0yWAW7xsq6OZqSX0SBUaLiQ8iMfueJjARFXHj04i8HMtjneHQopwL4jPpfYj4Zk7oNVSzkhpP3TZN8BkJCx2Ta4vPZfddPj5iRP4gNKuwnvyQK7ZbudY976UDTwc/o9vM9gSOyl/paY+tlvU9n0cWqu+6gg6h4cP9/Gtm5nHtHciSF72E2srlXJty2yY49JmEQfY4tlOToyZtXlWR36LHsk3ztH51Bun8UG6oo8UHhEIqWpPcU2UyAz5nhfuar33kMLINdbrISYFHtf2K6n2gadViCtCWaffXBzLoDKtmZfcd1zghMBxkpvwWuNAwv3CdFlXPQ3SSlnNCj7Yyzwd8w5PknJfAODthpIwxjhNKS2DgC7iYMMeixu9zj3oHhcBA50DpFB5xa5LajKahAUDy3HfniD428zVos45f1GYXNCCFkjbMMHdUMpgb8/JiSyZsW7F6x89AZOqxVJ72WcJzBWH5JIvtji4/J1ypN4e8psLtcYffBj2UN+yMHr/JbfnsjTizEj/OpAlcgKz2zwbeGlXBDJU= # BITBUCKET_USER_PASSWORD
    - name: FASTLANE_PASSWORD
    - secure: CglZmVTRiZsd6Ugpp777jd6dG+BDsDCbWIVth7852XKxNscu7UZmKfvrQ0ZcLN/jwpAnACwGRx93fcA2DgffAaZO+t65/YY8Xma4ybITrG+xwG5BhQVuA7GnH1oD8xbDoMiovS4muh35reKUqioipoey5lTkq4ZpnnX1MulFgA48Sum8lKOlh3U4al5p084Hs19TzoZWm64tIel6Ap8RXvfPFXkyNl2JNM+y+gyQoCQx16h4JRaNmX3SLrqFIQTxFxaheZxMvIo0EIu6vbdYV2MGFIXGjNmGYik16i8FefG0hdyxiclXdeQkxMOfwd/H34C/Z6A2XVk6PDeJE07AYSHEpO3C0btb1ggHlO3Izz2UCY2E/vKDqPGWqwRaR/X1LX/T+137as3MSC+1uB7aZo9DzYRWw2bk6xg6Xuu1lrq4+YgjCHy2Z/Jhj5b8Y913e9nD0grELkIyeOQheFXapPuBG7kzC7Q9K6DoUW7kVhKMXVWUlGAWywUIMaJMOe9Dj+vaVOFgCX9W7LAtQS1Adjzhe+0ifVFiKh57HoSICfg2yagwfljqMcax2VmP9HtkWNpnP3sX9oTHg5VoCuy168Qn1M1hdSbUxKOp1q5eUJ3oLiDoN0Hqlkk+iTAsEeGupHryJ0Fm2o8vJLDLIy4MDQQ3pClAh++Bq47T+wmoHuk= # FASTLANE_PASSWORD
    - name: BITBUCKET_BUILD_AUTH
    - secure: Kl+aaFeUSDMtRL3bU66P3ol/bKwhwOVZ6Q8YYcz6OUcqtsw+O27jis7XK3n8bVTmKbxwPEU5HZKESMgi3I4YzAlv8//S7wATJN1whK9HL9A0+XSyWQjsNqz3jyjGesXFQJ+EcSpMIAMG1MpyDrr91M5g0WMnloPO3+7PcCK78lkCfkh7jtEPsKHQCkpWWLe+a913W+In/EcujzkR2T/tLE4HKzEMn3XO++MSrf2ey7vYUJFF1WAWBKAf107t1KGB2DspxfRsMWT2oRRa1dkxFF/VDdD0tf34AYijH4c1Oc0WxH8faZpPsw+4BtgbcOQws4g7+GAqdQUutW5cfQVyi6N7I0ZfUYai0PZvZIZ+hsfIUc1bPOGya7U6k0nkt1agoSbWU8XGhnvrvYt/nuQNSfboJLMC2vTBiwMegt09kePACSOMFsLe9RJoDCbWUW4GSU58ThXokC96Hl6KoVI2XZqdpHwE+XOZDe3byscittEg2dJStDOHQZwwYAfwiic9J2YM3dr2ZxuOlLzMNPcllZD6SJv+9RU+eJ/PpuJ8R24mfjnljFTW9wP4E1iK9lnFfKlDUMN4fWMx8xBmggOSPGFwWv/aU8s0r30YpwR2T298UftwUfIHQNzkIMQtmoPbwuLIGR9tFeL/h+N5qBzdjqAcQsJUAdHPQFjKXR29boQ= # BITBUCKET_BUILD_AUTH
    - name: MATCH_PASSWORD
    - secure: Ts/HcS0FuNEyOCy2f1ip/CspbGiK/yXpdIIf9d0EctYcQIfBl4Ww00Ghx7L6ZrjpqdIInE1D6suTHXCWTB71wEBF+FCdqY+pZJHCNnsbj69MzFXGq86KhZkJyf1eFRAaRfY4K0PrhwNvd0UapsMIpTgSrdOtVahgwDIFDpcCKV0nrTd1Eg1puUB+MQI5kQRztGMuTPTWtrfhTvF/QxxJ9XRc2vdJHVveBx7b+1IqpTHoLkc7ixuzT5WyINlcCpj6YjnRbKeZZSATr0u4VLQA6y5LpAw2CMWpCXGY86nZmidYi7at1x8fR6EdD5c1nvZ0I2a8k+mhrTwYF1nc5gFYiyL8KB9xpk6K7sRIocSGu9m0DRuazFK5M5ubJvrlinW3KRKdkr+DrjXRTLTXOyUP+xqgY3j1aVuzMX9L7vatorOXhKi/xza5Axbxs61E9AFYV2nTUiXAa9TRvRQU9Flis3HErJwCnkehdP72SRiwCARirfieAUs0HSklo+JZDYTfm551UYnOJGMPzsKRmuv6nxw04xGywR036NgyADbUGY267YvxYMfjCWYewHJFRgkQ73HtRZdNvij+Boab8UTuAUC6ZxZOmsB3B8mlOQyLfZN0wO2akjQE8n+OPFYG2WeiDpQkggSKqH/T1DOr+CPN0iKx/DSBRdiGxCB3BpmkK5w= # MATCH_PASSWORD
git:
  submodules: false
before_install:
  # - |-
  #   echo -e "machine bitbucket.org
  #     login $BITBUCKET_USER_NAME
  #     password $BITBUCKET_USER_PASSWORD" > ~/.netrc
  # - git submodule update --init --recursive
  # - mv han-ios-app/* .
  # - echo -e "FASTLANE_PASSWORD=$FASTLANE_PASSWORD" > ~/.env
  # - gem install bundler
# cache:
#   bundler: true
#   cocoapods: true
#   directories:
#     - "$HOME/.rvm/"
#     # - "$HOME/.cocoapods/"
install: true
# script:
#   - bundle install --deployment
#   - bundle exec pod repo update
#   - bundle exec fastlane development

language: generic
os: linux

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode10.2
      env:
        - BUNDLE_GEMFILE: han-ios-app/Gemfile
      cache:
        bundler: true
        cocoapods: true
        directories:
          - "$HOME/.rvm/"
          - "$HOME/han-ios-app/vendor/bundle"
      before_install:
        - |-
          echo -e "machine bitbucket.org
            login $BITBUCKET_USER_NAME
            password $BITBUCKET_USER_PASSWORD" > ~/.netrc
        - ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
        - git submodule update --init --recursive
        - echo -e "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=$FASTLANE_PASSWORD" > $TRAVIS_BUILD_DIR/han-ios-app/fastlane/.env
        - |-
          echo 'FASTLANE_SESSION=---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value: DAWTKNV2f878172710e793d26a7a29ae22aefa612c2cc3e6c5ed74c1b4699c0859a7a3ddbb483420d4d424f3ee0a77106c8611966a14b0b6c0b04c829ebfea0a9ef8b1ea736ca0ef149bc778ac78626d5dabd40874fbc61d9e9f445bf3187c37e0701270ae794144d10105835945a642ab0cc57eadf742149f07a1f07f31243895b5af8b41b8b538ba65f82ed80f0577cf8e4ae943472514f62070b6323a7f9ed0144490e9dfb23d2387cd9568c66c64699d4c37173ae39d00eb9ddc2e2828b7c3044eb0d18a9e87c9c9a3d0810e6d5dac1997084ad5ecaf6361976eb2d4a6cfe20ec3d165ee1de26cc77fa3e361b4fabc11a9389f36343b93295313a1ab668e4a21cf9e30666664623638363334333766313162633437666364643065393838383434366337663034373637MVRYV2\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2019-04-17 10:01:24.580071000 -03:00\n  accessed_at: 2019-04-17 12:46:08.265757000 -03:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJ0QUwzaUczS3U4aldoR0tjMDBtYWRBIn0.UZ-N1Ou0P1avFgwOfqSnxp5NoJNPTAvpzqDAsCiBrWA\n  domain: appstoreconnect.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2019-04-17 12:46:09.457497000 -03:00\n  accessed_at: *1\n' >> $TRAVIS_BUILD_DIR/han-ios-app/fastlane/.env
        - rvm install 2.5.3
        - ./build-start.sh $BITBUCKET_BUILD_AUTH $(cd $TRAVIS_BUILD_DIR/han-ios-app ; git rev-parse HEAD) $TRAVIS_JOB_WEB_URL
      install:
        - rvm use 2.5.3
        - gem install bundler
        - bundle install --deployment --binstubs --gemfile=$BUNDLE_GEMFILE --path vendor/bundle
        - echo "Install iOS depentencies"
        - $TRAVIS_BUILD_DIR/han-ios-app/bin/fastlane -v
        - cd $TRAVIS_BUILD_DIR/han-ios-app
        - BUNDLE_GEMFILE=./Gemfile ./bin/fastlane development # --verbose
      script:
        - echo "Build iOS app with fastlane"
        - cd $TRAVIS_BUILD_DIR/han-ios-app
        - BUNDLE_GEMFILE=./Gemfile ./bin/fastlane snap # --verbose
      after_script:
        - $TRAVIS_BUILD_DIR/build-end.sh $BITBUCKET_BUILD_AUTH $TRAVIS_TEST_RESULT $(cd $TRAVIS_BUILD_DIR/han-ios-app ; git rev-parse HEAD) $TRAVIS_JOB_WEB_URL
