env:
  matrix:
  - secure: FY6RchLKeeKtDjQOlBB/kyPQBdx7laEBFK2xGONS76s/HJ0LMxOqPUivOnhoOJYMxx6H1+ax2iaWpTbbkxAACrcQ6w1lEqMF4NQAUbzhhfiAQiuYXOo45kmwCR1fb21VNNF8rQV8Yg+QU8oAUDPoN7nDnr0i2fzXArJI3sHtRqbFWjXMrpLTl6m4rXjwl5bGGVdMcKByrS3EXdwYv2pmBVY5zW5+dJIla/ebeXMxPdc8Ib3XgVcIKhhPDGvuodG4yoyQ82NQOf+N2+NfMXkZJ21I8MkNko/RB0I7iTf1DzOARi0pWW3FZb8YOMVxSzwE95ocz2pJrLtxqX+jPkgQBfFbC4ghoI5YyVuHafmjjkKbmOW0nivG/Fgr9/s1S5UGEMal82t+7DhWWfwp9lqrz2cHzo1VQe+4sMuhpEsM75FZczKdNg/Xoukbe1dk+9jpD4II7lA9GzNRpRdqC5lSlItzi+YNRXlnd0awWoN2cOc6q8MMxltbSxAxQ15MyQVHq6E0Tz/TSSp++H8XiwsiOk6of+gmdR0rZISM3FF2jM3+OYkSneskze9vBnoXrZtUokGAJxAeZICE7YaCqU5EySFXCx9+KgfI9J0MDXwpWNzwpJwsTFHcLww1jilxslsQw7IDO6ODQF4YylmvwEw+44Tw4QdTgzkcwFEGbrnE/AQ=
git:
  submodules: false
before_install:
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD"
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD" > ~/.netrc
  - git submodule update --init --recursive
  - gem install bundler
os: osx
language: swift
podfile: han-ios-app/Podfile
script:
  - cd han-ios-app
  - gem install bundler
  - bundle install
  - fastlane development
