env:
  global:
    secure: iMGc8NeoAukisjEqa7qkRUk7NEhbj2D1Rf/AyzMVO6AGZnJn5nPEJ/Igy+t+B2Py0doK7w4QpCij95dxSHXS8eeyu7bocymNmOkSGE1GlA9ifp4EekAvZL3SwLf/9EBEGOROYnJg073EeFgchzSK3EnZ2KfM3fgSLnksb+U9t9uVFsz+yyNRy91+XrW0k0unjTRiHfQV/lWCsyFBBErlTpJOFhXt4u84F/smZWPdU+ggkC7ic2gtIQHL6LY6zELxlUfXv/F95IpnRpUsXxTH4KcAAT5sOR3aedrm7HOXGCzTp6jnzZrVlAEHfTTSD2aqygzN9+bpK77lhUoFoRkaD8Xh2xQFrBdxNupvan1nsVbPH/2w/a1mcWrpE4PZRG8PiB8649tp/2If/sj4xcDYYGh5SQE9N7UfdmPLz7Myz+YhpDc+9LWbQWUvvxhIVlQqY2QCHbSSmc0LnqQnINj8iXXXJ7pVH6JxbSaGvN1dC3ZxV2v91+M3Rdgm82B/HEI1Wu/DRX7LZyL9PyVcXObbULhCjnOBsnL8q7dXv7+OXvlgVSaE5afQM0EHLo42MPeu1O2SuMdrH4W4kON01I46YfFyhPnx4NVU8soJrYI7NiaFia0ze2RiQCxvWsqPSk+HNDOup9tdhKhWbrzRiRIELI0/YwD6Hy+D11J10KuO4L8=
git:
  submodules: false
before_install:
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD"
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD" > ~/.netrc
  - git submodule update --init --recursive
  - mv han-ios-app/* .
  - gem install bundler
os: osx
language: swift
cache:
  bundler: true
  cocoapods: true
  directories:
    - /home/travis/.rvm/
    - $HOME/.cocoapods/
install: true
script:
  - bundle install --deployment
  - pod repo update
  - fastlane development
