env:
  global:
    - secure: PhopgnQgfNwczM/Vk5U7Ky6unvG5rCVSXocI6N16a8XquMt2dLc84p4DZDKb6TzT8BupKAKmnficL54Z9ESwSzoUo4GEzgsWgRru5/nwi39o1rg4Cnnu2l2+QLwR26LvXhc+QIaY7DCcyRD6NY/jfNV1rpvZzeLxGmanSW6DGjOmivFEh6FyZpfFZAPfI5VVXeePmlGi+icHGfLV2LKMizriQpgTnttuEPU8auwZsqYbp8zKO544OVR4SzdqOmKluat6hBsvGtHx0/NbqSUoSLVnRZmEsLrSODwTPvIXVwq14bTDZGznc2KowzsksoomoQpwOhClUcwCnv0Gn1sSxUNM1XN9eXdqtlbj5zx7Z0HfHcFaFjQR1NuIEc5WHrlXgdQpf1Mzqcee/R3n6lO9o4BAibCWIGJqJ9EwqiVHg+8mUQvHApnnmYpiggyNTAf2Hqr83To5TThnYchqvFbJ4TMA74cN4iFVFxAOFmRm42Xb57l0Fbc9Kud1V+YXkkqQZxfHfK/mRi/pyJCwzE3OGPpFAfBhOH1rJ5EibP9I52i2cDVdnvV91Hv/Su9tcMD+uNhDQ1EIM0+KIZFAA7WKvDLyO2zMAo2WcpWag5RSLu0wr2YsVTm8Eo3Lz/xsZUS2tH+EYCnrZntCBfL6xfnoP5WO5AV531wxoo5QU2m9rYU=
git:
  submodules: false
before_install:
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD"
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD" > ~/.netrc
  - git submodule update --init --recursive
  - mv han-ios-app/* .
  - gem install bundler
os: osx
language: swift
cache:
  bundler: true
  cocoapods: true
  directories:
    - "/home/travis/.rvm/"
    - "$HOME/.cocoapods/"
install: true
script:
  - bundle install
  - pod repo update
  - fastlane development
