env:
  global:
    - name: BITBUCKET_USER_NAME
    - secure: duCf4j0NVm/JdYCOa5PsX7MUBncl326iiMXPG7eOSSSgzYDxsV+7f8O43Ui6KeDLJT29dEU+fTe5ege49skGjWrDiXLbYShxxMd1DJx/ulPxynvrm90O07UHltPlMYl9HztwGqkB0p6WlN4yHiUf2tAYS6u5a5UWYbbrQvjIa3LlHlYfnqoC1fbneBn44cL/j79ukSQrGoyNSsvqbBMOkVsrIixTaHeWNumP75Kv5z9cWRUOtuY507bQA9Aj8sYvrKRAjXTB+ey4tyb1aD2u6JYStFsKC4133W91kttc+D3YHfpWdEwe14R7/XPL2n+euzRQhVr4miR+F/1pXSoAvqPlPWi9KhXlhlHas7JRL40SeGmOuERX+lyFz4kG72rE/eRTJLxEpHB16BdW30fENpUZ0zCQuiSORdmigD4glowxtf6vX7KcKlHvtw3X2axjTFzPKAbL60v1t4HgE9eL2ZW2pTYnik/GT3zMA3xLYSxOUW4x0dAlOtskLEf1fFfMVZkg+mJflp2LfYgwIh/Ddn1HQZYbYoyx4kgG6LXRvKU1ZQFWSbjNYZUm/g5pReBp3+cR1ZOZiIkk2YaUpcrtlFazOj2ieXD21OBo0m5GaEyzrPaU7ZyiOBzMt9olTILmjxTfnIlUJQJr1yo2Jzf3hKEFpRTmeJYFtGqs+bJQKrA= # BITBUCKET_USER_NAME
    - name: BITBUCKET_USER_PASSWORD
    - secure: jwnuTcfHyjjJkEtRDBAVua68bt1Tygtw6qy4Qkf1hB5lq04ehvBVEqH+oAjdjl+wNqmyeGkt8E7wdAs3K+3eURbHlxBO/1hQyf2VZZz0JwTJyl/dt3eBuinHq5ZoUaKO69+rvp2AB8MIM8C0yWAW7xsq6OZqSX0SBUaLiQ8iMfueJjARFXHj04i8HMtjneHQopwL4jPpfYj4Zk7oNVSzkhpP3TZN8BkJCx2Ta4vPZfddPj5iRP4gNKuwnvyQK7ZbudY976UDTwc/o9vM9gSOyl/paY+tlvU9n0cWqu+6gg6h4cP9/Gtm5nHtHciSF72E2srlXJty2yY49JmEQfY4tlOToyZtXlWR36LHsk3ztH51Bun8UG6oo8UHhEIqWpPcU2UyAz5nhfuar33kMLINdbrISYFHtf2K6n2gadViCtCWaffXBzLoDKtmZfcd1zghMBxkpvwWuNAwv3CdFlXPQ3SSlnNCj7Yyzwd8w5PknJfAODthpIwxjhNKS2DgC7iYMMeixu9zj3oHhcBA50DpFB5xa5LajKahAUDy3HfniD428zVos45f1GYXNCCFkjbMMHdUMpgb8/JiSyZsW7F6x89AZOqxVJ72WcJzBWH5JIvtji4/J1ypN4e8psLtcYffBj2UN+yMHr/JbfnsjTizEj/OpAlcgKz2zwbeGlXBDJU= # BITBUCKET_USER_PASSWORD
    - name: FASTLANE_PASSWORD
    - secure: CglZmVTRiZsd6Ugpp777jd6dG+BDsDCbWIVth7852XKxNscu7UZmKfvrQ0ZcLN/jwpAnACwGRx93fcA2DgffAaZO+t65/YY8Xma4ybITrG+xwG5BhQVuA7GnH1oD8xbDoMiovS4muh35reKUqioipoey5lTkq4ZpnnX1MulFgA48Sum8lKOlh3U4al5p084Hs19TzoZWm64tIel6Ap8RXvfPFXkyNl2JNM+y+gyQoCQx16h4JRaNmX3SLrqFIQTxFxaheZxMvIo0EIu6vbdYV2MGFIXGjNmGYik16i8FefG0hdyxiclXdeQkxMOfwd/H34C/Z6A2XVk6PDeJE07AYSHEpO3C0btb1ggHlO3Izz2UCY2E/vKDqPGWqwRaR/X1LX/T+137as3MSC+1uB7aZo9DzYRWw2bk6xg6Xuu1lrq4+YgjCHy2Z/Jhj5b8Y913e9nD0grELkIyeOQheFXapPuBG7kzC7Q9K6DoUW7kVhKMXVWUlGAWywUIMaJMOe9Dj+vaVOFgCX9W7LAtQS1Adjzhe+0ifVFiKh57HoSICfg2yagwfljqMcax2VmP9HtkWNpnP3sX9oTHg5VoCuy168Qn1M1hdSbUxKOp1q5eUJ3oLiDoN0Hqlkk+iTAsEeGupHryJ0Fm2o8vJLDLIy4MDQQ3pClAh++Bq47T+wmoHuk= # FASTLANE_PASSWORD
git:
  submodules: false
before_install:
  - |-
    echo -e "machine bitbucket.org
      login $BITBUCKET_USER_NAME
      password $BITBUCKET_USER_PASSWORD" > ~/.netrc
  - git submodule update --init --recursive
  - mv han-ios-app/* .
  - echo -e "FASTLANE_PASSWORD=$FASTLANE_PASSWORD" > ~/.env
  - gem install bundler
os: osx
language: swift
cache:
  bundler: true
  cocoapods: true
  directories:
    - "$HOME/.rvm/"
    - "$HOME/.cocoapods/"
install: true
script:
  - bundle install --deployment
  - bundle exec pod repo update
  - bundle exec fastlane development
